# Site settings
title: Entrepreneur TV
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Creating a startup that will change the world? You're in a toxic ecosystem? Learn the shortcuts to make your startup successful and dominate its market."
baseurl: ""
url: ""
twitter_username: jorisrenaud
github_username:  jorisrenaud
facebook_username: jorisrenaud

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Pagination
gems: [jekyll-paginate]
paginate: 40
paginate_path: "page:num"


